### ISSUE TITLE
[feature] Add bun as a package manager 

### ISSUE THREAD

**Issue by hckhanh** [moonrepo/moon#1074]
**Is your feature request related to a problem? Please describe.**

I intend to use moon with bun as a package manager. But it only supports npm, yarn and pnpm for now according to the docs

**Comment by milesj** [comment]
@hckhanh Integrated bun support won't happen for a long time, since it'll require a ton of work. It's not as simply as add `bun` to the `packageManager` setting, because Bun is it's own runtime, not a package manager for Node.

If you want to use `bun` in general, you can do just that though: https://moonrepo.dev/docs/faq#can-we-run-other-languages

**Comment by hckhanh** [comment]
Thank you @milesj, I hope it will be planned someday.

**Comment by milesj** [comment]
In 1.16!
