### ISSUE TITLE
[feature] Better validation for workspace.yml

### ISSUE THREAD

**Issue by rotu** [moonrepo/moon#1179]
**Is your feature request related to a problem? Please describe.**

I tried to define a `workspace.yml` using vcs.manager = "hg". Since Mercurial is not supported, I got the following error message:

```
moon sync
Error: config::parse::failed

  × Failed to parse .moon\workspace.yml.
  ╰─▶   × vcs.manager: unknown variant `hg`, expected `git`
```

**Describe the solution you'd like**

- Validation should possibly link to the documentation at https://moonrepo.dev/docs/config/workspace
- The error message should show that `null` is accepted (which it is, according to the schema)
- The documentation should mention whether `null` means no VCS or default VCS (i.e. git)

**Comment by milesj** [comment]
A lot of this is abstracted away from us, like the error messages. We don't control those at all, they come from Rust's serde crate. And also because of Rust, dynamically inserting URLs for each field isn't possible, and manually adding them to each field feels like a maintenance headache. I can see the benefit of having this info though.

I'm honestly not sure how the Rust yaml/serde stuff handles an explicit `null`, I've never tested it. I'm guessing it unsets the field, which then results in the default value being used instead? But of course not setting the field at all will use the default.

**Comment by milesj** [comment]
Yeah I can probably do that with the URL. Let me take a look.

**Comment by milesj** [comment]
v1.18 now includes links
